### ISSUE TITLE
[update required] update_cases does not accept project_id now in latest APIs, it should be removed

### ISSUE THREAD

**Issue by jaikantCS** [tolstislon/testrail-api#86] opened 2023-01-16 16:40 UTC
**Version**: 1.11.1
**Problem statement**: When you try to update the fields for multiple tests using **update_cases** method, it does send the valid payload.
Current implementation is ``` def update_cases(
        self, project_id: int, suite_id: Optional[int] = None, **kwargs
    )```

But it should no longer use **project_id**  as its no longer required as per new documentation of TestRail API.https://support.gurock.com/hc/en-us/articles/7077292642580-Cases#updatecases

I can see that the code present on github is using the latest format 
    ```def update_cases(self, case_ids: List[int], suite_id: int, **kwargs) -> dict:```
https://github.com/tolstislon/testrail-api/blob/97b32e7447ab22c75aa2bbc9049df2f74b0f7f38/testrail_api/_category.py#L504

But the zip archive still uses the previous format and thus the request does not success and we get error. When I try to install the pip package, it downloads the older code.

Maybe there is no new build after this change or the last one failed not sure. But you can check in the archives, it still uses the previous version code and is not latest.

Can you please rebuild the project with the code present on current repository.

Thanks!

**Comment by dsayling** [comment] 2023-01-20 19:34
Dupe of #63 

Fix is in #76 

@tolstislon - when do you plan on doing the next release?

**Comment by jaikantCS** [comment] 2023-01-23 15:16
thanks for the info guys 🙏 .appreciate it

**Closed as completed** 2023-01-23 17:40 UTC

**Comment by jaikantCS** [comment] 2023-01-23 18:04
No worries, You guys are awesome :)
The library is truly a time saver. Have a good week ahead!
